spring:
  datasource:
    url: jdbc:h2:mem:d:/Data/test;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
    #schema: classpath:db/schema.sql  #进行该配置后，每次启动程序，程序都会运行resources/db/schema.sql文件，对数据库的结构进行操作。用jpa的话这个就不需要了
    data: classpath:db/data.sql      #进行该配置后，每次启动程序，程序都会运行resources/db/data.sql文件，对数据库的数据操作。
    platform: h2    #h2 web console设置 表明使用的数据库平台是h2
  h2:
    console:
      settings:
        web-allow-others: true  # 进行该配置后，h2 web consloe就可以在远程访问了。否则只能在本机访问。
      path: /h2-consle  #进行该配置，你就可以通过YOUR_URL/h2访问h2 web consloe。YOUR_URL是你程序的访问URl。
      enabled: true #进行该配置，程序开启时就会启动h2 web consloe。当然这是默认的，如果你不想在启动程序时启动h2 web consloe，那么就设置为false。